### ISSUE TITLE
ERROR: No delay bar sprite for delay 7

### ISSUE THREAD

**Issue by Cethin** [PleasingFungus/Silicon-Zeroes#107] opened 2017-10-02 22:14 UTC
Version: 1.1.1.0-g68c7f0c4

Error occurs when an O-Sel is increased to size 7. Does not occur on any other value. If an 8 is entered rather than dragging through 7 there is no error.

I assume this will happen any time a delay of 7 appears.

To Reproduce: Increase an O-Sel to size 7 on any level with delay. Any level in High Speed with O-Sel available has this problem.

![image](https://user-images.githubusercontent.com/9389721/31101862-81f2adaa-a79d-11e7-93c4-c011c13b0d18.png)

**Comment by PleasingFungus** [comment] 2017-10-02 22:15
Already fixed in 5f13aaa41; will be out in a hotfix later today. (Duplicate of #106 .)

Very sorry for the trouble!

**Closed by PleasingFungus** 2017-10-02 22:15 UTC

**Comment by Cethin** [comment] 2017-10-02 22:35
Thanks for the update. Luckily it wasn't much of an inconvenience because there isn't much of a need for 7. Thanks for making this game! I love it and was working on something very similar that I never had time to finish. Glad someone came along and did it.
